version: "3.7"

services:
  postgresql:
    container_name: postgresql
    image: debezium/postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: on-failure

  mysql:
    container_name: mysql
    image: mysql:latest
    ports:
      - 3306:3306
    volumes:
      - ./config/mysql:/etc/mysql/conf.d/
    environment:
      - MYSQL_ROOT_PASSWORD=root1234
      - MYSQL_DATABASE=debezium
      - MYSQL_USER=userdemo
      - MYSQL_PASSWORD=userpwd
    restart: on-failure

  redis:
    container_name: redis
    image: redislabs/redismod
    ports:
      - 6379:6379
    restart: on-failure

  redisinsight:
    image: redislabs/redisinsight
    container_name: redisinsight
    ports:
      - 8001:8001
    depends_on:
      - redis
    restart: on-failure